# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

#trigger:
#- main

#resources:
#- repo: self

#variables:
#  tag: '$(Build.BuildId)'

#stages:
#- stage: Build
  #displayName: Build image
  #jobs:
  #- job: Build
    #displayName: Build
    #pool: Default
    #steps:
    #- task: Docker@2
      #displayName: Build an image
      #inputs:
        #command: build
        #dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
        #tags: |
          #$(tag)
pool: linux

container: ubuntu:18.04

steps:
- script: printenv
#pool: Default

#strategy:
#  matrix:
#    ubuntu16:
#      containerImage: ubuntu:16.04
#    ubuntu18:
#      containerImage: ubuntu:18.04
#    ubuntu20:
#      containerImage: ubuntu:20.04

#container: $[ variables['containerImage'] ]

#steps:
#- script: printenv

#container:
#  image: registry:ubuntu1804
#  endpoint: private_dockerhub_connection

#steps:
#- script: echo hello

#container:
#  image: ubuntu:18.04
#  options: --hostname container-test --ip 192.168.0.1

#steps:
#- script: echo hello
#resources:
#  containers:
#  - container: u16
#    image: ubuntu:16.04

#  - container: u18
#    image: ubuntu:18.04

#  - container: u20
#    image: ubuntu:20.04

#jobs:
#- job: RunInContainer
#  pool:
#    vmImage: 'ubuntu-latest'

#  strategy:
#    matrix:
#      ubuntu16:
#        containerResource: u16
#      ubuntu18:
#        containerResource: u18
#      ubuntu20:
#        containerResource: u20

#  container: $[ variables['containerResource'] ]

#  steps:
#  - script: printenv