# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

#trigger:
#- main

#resources:
#- repo: self

#variables:
#  tag: '$(Build.BuildId)'

#stages:
#- stage: Build
  #displayName: Build image
  #jobs:
  #- job: Build
    #displayName: Build
    #pool: Default
    #steps:
    #- task: Docker@2
      #displayName: Build an image
      #inputs:
        #command: build
        #dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
        #tags: |
          #$(tag)
#pool: linux

#container: ubuntu:18.04

#steps:
#- script: printenv
pool: Default

strategy:
  matrix:
    ubuntu16:
      containerImage: ubuntu:16.04
    ubuntu18:
      containerImage: ubuntu:18.04
    ubuntu20:
      containerImage: ubuntu:20.04

container: $[ variables['containerImage'] ]

steps:
- script: printenv